export const configColor = {
    key_color: '#e9fb47',
    top_menu_icon_color: '#000000',
    button_background: '#ff9800',
    button_text_color: '#ffffff',
    menu_background: '#d65555',
    menu_text_color: '#ffffff',
    menu_line_color: '#292929',
    menu_icon_color: '#ffffff',
    search_box_background: '#f3f3f3',
    search_text_color: '#7f7f7f',
    app_background: '#ffffff',
    content_color: '#7b74c7',
    image_border_color: '#f5f5f5',
    line_color: '#e8e8e8',
    price_color: '#ab452f',
    special_price_color: '#ab452f',
    icon_color: '#717171',
    section_color: '#f8f8f9',
    status_bar_background: '#000000',
    status_bar_text: '#000000',
    loading_color: '#000000',
    // splash_screen_color : window.DEFAULT_COLORS.splash_screen_color ? window.DEFAULT_COLORS.splash_screen_color : '#fff',
    // loading_splash_screen_color : window.DEFAULT_COLORS.loading_splash_screen_color ? window.DEFAULT_COLORS.loading_splash_screen_color : '#000',
};
